### ISSUE TITLE
Incorrect SDF equation?

### ISSUE THREAD

**Issue by kosukesando** [JakeGrainger/OceanWaveSpectralFitting.jl#9]
Is the 1/2 at the end a typo or something I missed? It doesn't match the description of the equation in the documentation.
https://jakegrainger.github.io/OceanWaveSpectralFitting.jl/stable/univariate/#OceanWaveSpectralFitting.JONSWAP

https://github.com/JakeGrainger/OceanWaveSpectralFitting.jl/blob/7ff367f7d5a8b7e05702f084559709ace71b636d/src/models/univariate/JONSWAP.jl#L74C1-L74C76

**Comment by JakeGrainger** [comment]
Ah yes its a typo in the docs, well spotted I have just updated this. It is because the models were originally defined as one sided spectra (so they only include positive frequencies and have twice the density, but the package uses the two sided version
